name: superlinter

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: '14.x'

    steps:
    - uses: actions/checkout@v2
    - name: Use superlinter ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test